name: hbcgm
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bedtools
  - deeptools
  - gsl
  - ipython
  - matplotlib
  - numpy
  - pandas
  - pysam
  - python
  - samtools
  - scikit-learn
  - scipy
  - seaborn
  - snakemake
  - tqdm
  - yaml


