name: hbcgm
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _py-xgboost-mutex
  - aioeasywebdav
  - aiohttp
  - alsa-lib
  - anaconda-client
  - anndata
  - appdirs
  - argcomplete
  - argh
  - asciitree
  - aspera-cli
  - astroid
  - async-timeout
  - atactk
  - attrs
  - backcall
  - bcrypt
  - bedtools
  - binutils_impl_linux-64
  - binutils_linux-64
  - biopython
  - bleach
  - blosc
  - bokeh
  - boost-cpp
  - boruta_py
  - boto3
  - botocore
  - brotlipy
  - bwa
  - bwidget
  - bx-python
  - bzip2
  - ca-certificates
  - cachetools
  - cairo
  - certifi
  - cffi
  - chardet
  - click
  - cloudpickle
  - clyent
  - colorcet
  - colormath
  - conda
  - conda-package-handling
  - configargparse
  - cooler
  - cryptography
  - curl
  - cycler
  - cython
  - cytoolz
  - dask
  - dask-core
  - datrie
  - dbus
  - decorator
  - deeptools
  - deeptoolsintervals
  - defusedxml
  - dill
  - distributed
  - docutils
  - dropbox
  - entrypoints
  - expat
  - fastp
  - fastqc
  - fftw
  - filechunkio
  - flask
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-forge
  - freetype
  - fribidi
  - fsspec
  - ftputil
  - future
  - gcc_impl_linux-64
  - gcc_linux-64
  - gdk-pixbuf
  - get_version
  - gettext
  - gffutils
  - gfortran_impl_linux-64
  - gfortran_linux-64
  - ghostscript
  - giflib
  - gitdb
  - gitpython
  - glib
  - gobject-introspection
  - google-api-core
  - google-auth
  - google-cloud-core
  - google-cloud-storage
  - google-resumable-media
  - googleapis-common-protos
  - graphite2
  - graphviz
  - gsl
  - gst-plugins-base
  - gstreamer
  - gxx_impl_linux-64
  - gxx_linux-64
  - h5py
  - harfbuzz
  - hdf5
  - heapdict
  - hicmatrix
  - htslib
  - icu
  - idna
  - imagemagick
  - importlib-metadata
  - importlib_metadata
  - intermine
  - intervaltree
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - itsdangerous
  - jbig
  - jedi
  - jinja2
  - jmespath
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - kiwisolver
  - krb5
  - lazy-object-proxy
  - lcms2
  - ld_impl_linux-64
  - legacy-api-wrap
  - libblas
  - libcblas
  - libclang
  - libcroco
  - libcurl
  - libdeflate
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgomp
  - libiconv
  - liblapack
  - libllvm8
  - libllvm9
  - libopenblas
  - libpng
  - libprotobuf
  - librsvg
  - libsodium
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libtool
  - libuuid
  - libwebp
  - libwebp-base
  - libxcb
  - libxgboost
  - libxkbcommon
  - libxml2
  - libxslt
  - llvmlite
  - locket
  - lz4-c
  - lzo
  - lzstring
  - make
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-venn
  - mccabe
  - mistune
  - mock
  - msgpack-python
  - multidict
  - multiprocess
  - multiqc
  - natsort
  - nbconvert
  - nbformat
  - ncbi-ngs-sdk
  - ncurses
  - networkx
  - notebook
  - nspr
  - nss
  - numba
  - numexpr
  - numpy
  - olefile
  - openblas
  - openjdk
  - openjpeg
  - openssl
  - packaging
  - pairix
  - pandas
  - pandoc
  - pandocfilters
  - pango
  - param
  - paramiko
  - parso
  - partd
  - patsy
  - pcre
  - pcre2
  - perl
  - perl-app-cpanminus
  - perl-business-isbn
  - perl-business-isbn-data
  - perl-carp
  - perl-constant
  - perl-data-dumper
  - perl-encode
  - perl-exporter
  - perl-extutils-makemaker
  - perl-file-path
  - perl-file-temp
  - perl-mime-base64
  - perl-parent
  - perl-uri
  - perl-xml-libxml
  - perl-xml-namespacesupport
  - perl-xml-sax
  - perl-xml-sax-base
  - perl-xsloader
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - pkg-config
  - plink
  - plotly
  - prettytable
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - protobuf
  - psutil
  - pthread-stubs
  - ptyprocess
  - py-xgboost
  - py2bit
  - pyasn1
  - pyasn1-modules
  - pybigwig
  - pycairo
  - pycosat
  - pycparser
  - pyct
  - pyct-core
  - pyfaidx
  - pygenometracks
  - pygments
  - pygraphviz
  - pylint
  - pynacl
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysam
  - pysftp
  - pysocks
  - pytables
  - python
  - python-dateutil
  - python-irodsclient
  - python-levenshtein
  - python-lzo
  - python-pdfkit
  - python_abi
  - pytz
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - qtpy
  - ratelimiter
  - readline
  - requests
  - retrying
  - rise
  - rsa
  - ruamel_yaml
  - s3transfer
  - salmon
  - samblaster
  - samtools
  - scanpy
  - scikit-learn
  - scipy
  - seaborn
  - sed
  - send2trash
  - setuptools
  - setuptools-scm
  - setuptools_scm
  - sexpdata
  - shapeit4
  - simplejson
  - six
  - smmap
  - snakemake
  - snakemake-minimal
  - sortedcontainers
  - spectra
  - sqlite
  - sra-tools
  - star
  - statsmodels
  - sysroot_linux-64
  - tbb
  - tblib
  - terminado
  - testpath
  - tk
  - tktable
  - toml
  - toolz
  - toposort
  - tornado
  - tqdm
  - traitlets
  - typed-ast
  - typing_extensions
  - umap-learn
  - urllib3
  - vcftools
  - wcwidth
  - webencodings
  - werkzeug
  - wheel
  - widgetsnbextension
  - wkhtmltopdf
  - wrapt
  - xgboost
  - xlrd
  - xlwt
  - xmlrunner
  - xmltodict
  - xorg-fixesproto
  - xorg-inputproto
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-libxpm
  - xorg-libxrender
  - xorg-libxt
  - xorg-libxtst
  - xorg-recordproto
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - yarl
  - zeromq
  - zict
  - zipp
  - zlib
  - zstd


