
# files
GENOME: "/home/fangzq/genome/mouse/GRCm38_68.fa"
dbSNP: "/home/fangzq/genome/mouse/mgp.v5.merged.snps_all.dbSNP142.sorted.vcf"
dbINDEL: "/home/fangzq/genome/mouse/mgp.v5.merged.indels.dbSNP142.normed.vcf"
BAM_DIR: "/data/bases/fangzq/strains"
TMPDIR: "/home/fangzq/TMPDATA"
# raw fastq files
FASTQS:
    PATH: ""
    # regex pattern of fastq files
    # exact 3 group for example: name, lane
    R1: "([A-Z0-9-]+)_(L[0-9]{3})_R1_[0-9]{3}.fastq.gz"
    R2: "([A-Z0-9-]+)_(L[0-9]{3})_R2_[0-9]{3}.fastq.gz"

STRAINS: ['129P2', '129S1', '129S5', 'AKR', 'A_J', 'B10', 
        'BPL', 'BPN', 'BTBR', 'BUB', 'B_C', 'C3H', 'C57BL10J',
        'C57BL6NJ', 'C57BRcd', 'C57LJ', 'C58', 'CBA', 'CEJ', 
        'DBA', 'DBA1J', 'FVB', 'ILNJ', 'KK', 'LGJ', 'LPJ', 
        'MAMy', 'MRL','NOD', 'NON', 'NOR', 'NUJ', 'NZB', 'NZO', 'NZW', 
        'PJ', 'PLJ', 'RFJ', 'RHJ', 'RIIIS', 'SEA', 'SJL', 'SMJ', 'ST', 'SWR', 'TALLYHO', 'RBF',
        'CAST', 'MOLF', 'PWD','PWK', 'SPRET', 'WSB'] 

HBCGM:
    # working directory
    WORKSPACE: "/data/bases/fangzq/MPD/results_drug_diet"
    # path to haplomap
    BIN: "/home/fangzq/github/HBCGM/build/bin"
    
    # ghmap input
    # MPD trait ids 
    TRAIT_IDS: "/data/bases/fangzq/MPD/drug-diet.ids.txt"
    # set to true if input individual animal data. Default: use strain means.   
    USE_RAWDATA: false 
    # given file path, use input data instead of using MPD API to get data.
    TRAIT_DATA:  "" #"/data/bases/shared/haplomap/AHresponse_strainmeans2.txt"
    # genetic relation file from PLink output
    GENETIC_REL: "/data/bases/shared/haplomap/PELTZ_20200429/mouse54_grm.rel"
    GENETIC_REL_ID: "/data/bases/shared/haplomap/PELTZ_20200429/mouse54_grm.rel.id"
    # gene expression file
    GENE_EXPRS: "/data/bases/shared/haplomap/PELTZ_20200429/mus.compact.exprs.txt"
    # open chromatin regions to annotate haploblocks.
    ATAC_PEAKS: "/data/bases/fangzq/MouseEpigenomeAtlas/beds/*.blacklist_removed.broadPeak"

    # eblock input
    # strains metadata. 
    STRAIN_ANNO: "/data/bases/shared/haplomap/PELTZ_20200429/strains.metadata.csv"
    # path to SNP database
    SNPS_DIR: "/data/bases/shared/haplomap/PELTZ_20200429/SNPs"
    # SNP annotations for all genes
    ANNOVAR: "/data/bases/shared/haplomap/PELTZ_20200429/AA_by_strains.pkl" 
    KNOWNGENE_META: "/data/bases/shared/haplomap/PELTZ_20200429/mm10_kgXref.txt" 
    KNOWNGENE: "/data/bases/shared/haplomap/PELTZ_20200429/mm10_knownGene.txt" 


GATK:
    WORKSPACE: "/data/bases/fangzq/20200430_GATK"
    qual: 50 
    heterzygote_cutoff: 20
    # for hardfilering, no implemented yet
    snp:
        - "-filter 'QD < 2.0' --filter-name 'QD2' " 
        - "-filter 'QUAL < 30.0' --filter-name 'QUAL30' " 
        - "-filter 'SOR > 3.0' --filter-name 'SOR3' " 
        - "-filter 'FS > 60.0' --filter-name 'FS60' " 
        - "-filter 'MQ < 40.0' --filter-name 'MQ40' " 
        - "-filter 'MQRankSum < -12.5' --filter-name 'MQRankSum-12.5' " 
        - "-filter 'ReadPosRankSum < -8.0' --filter-name 'ReadPosRankSum-8' " 
    indel:
        - "-filter 'QD < 2.0' --filter-name 'QD2' " 
        - "-filter 'QUAL < 30.0' --filter-name 'QUAL30' " 
        - "-filter 'FS > 200.0' --filter-name 'FS200' " 
        - "-filter 'ReadPosRankSum < -20.0' --filter-name 'ReadPosRankSum-20' " 

BCFTOOLS:
    WORKSPACE: "/data/bases/fangzq/20200429_BCFTOOLS"
    qual: 50 
    heterzygote_cutoff: 20
    

